### ISSUE TITLE
Going for a hard table

### ISSUE THREAD

**Issue by madig** [simoncozens/fonttools-rs#2]
I like the use of serde! I wonder if it's going to work for all tables, though?

I remember @behdad mentioning somewhere (around https://github.com/yeslogic/allsorts discussion somewhere) that attempts to build a new OT parser should try to implement complete support for a specific table first because it is the hardest to implement and all other decisions can flow from there. I think it was GPOS?

**Comment by simoncozens** [comment]
It's a good idea, if you already know the language well. :-) I feel out of my depth in Rust so am building up my confidence by implementing things from bottom up and doing a little happy dance when they work.

Behdad is probably right, but in a way I think it's more important to get particular parser/serializer elements working:

* Counted arrays where the count is immediately before the array (serialization done already)
* Counted arrays where the count is in an element earlier in the struct (e.g. fvar)
* Counted arrays where the count is in an external table (hmtx)
* Offset-indexed structs
* Offset-indexed arrays
* ...

I don't expect to be able to use serde derives for all tables; we will need to manually serialise/deserialize some of them. But where we can, we definitely should.

**Comment by simoncozens** [comment]
I've done gvar now. Man, that was hard enough. GSUB/GPOS are actually pretty easy because they're all fairly standard and self-contained.
