### ISSUE TITLE
fontcrunch is slow because I can't handle references and lifetimes

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/fonttools-rs#35]
The ported version of fontcrunch is much slower than the original, particularly in glyphs which go down this O(n^2) loop:

https://github.com/simoncozens/fonttools-rs/blob/0400715da315aa783c57070da2897760694b1fc3/crates/fonttools-cli/src/bin/fontcrunch.rs#L322-L332

I'm sure it's because of this clone:

https://github.com/simoncozens/fonttools-rs/blob/0400715da315aa783c57070da2897760694b1fc3/crates/fonttools-cli/src/bin/fontcrunch.rs#L366

The clone is only there because I can't work out the lifetimes required for storing `Statelet`s as references within a `Statelet` and moving them around. If I put what I think are the right lifetimes on the State and Statelet types, I get a confusing error like so:

```
431 |     states: &mut Vec<State>,
    |             --------------- these two types are declared with different lifetimes...
...
454 |         states[this].sts.push(sl);
    |                               ^^ ...but data from `states` flows into `states` here
```

**Comment by simoncozens** [comment]
@cmyr If you have any advice I would appreciate it. :-/

**Comment by cmyr** [comment]
Can take a look in a few minutes. 👍

**Comment by cmyr** [comment]
avoiding a linked list is definitely the first thing I would try. taking a look now, will see if I have any more concrete advice..

**Comment by simoncozens** [comment]
Original C++ is here if it helps: https://github.com/googlefonts/fontcrunch/blob/main/src/fontcrunch/quadopt.cc

I just realised one of the Vec's was being used as an Option, so fixed that.

**Comment by cmyr** [comment]
There's a lot going on here, and I don't know a ton of the details, but some thoughts:

if any of these vecs are fixed size, or have generally small sizes, I would look into using either an array or some sort of 'smallvec' type, like [`smallvec`](https://docs.rs/smallvec/1.6.1/smallvec/).

Instead of a linked list, my first thought would be to have a big shared vec (or `Rc<[]>`) of statelets, and then instead of passing around statelets themselves you'd pass around indices into this big shared sequence?

**Comment by simoncozens** [comment]
Thanks for this. I have now switched it to using an Rc to hold the Statelet to ensure copies are cheap, but the performance problem is the same, so my intuition (copying the statelet lots of time was slow) doesn't seem to have been correct. Time to actually use a profiler and find out what's going on.

**Comment by simoncozens** [comment]
OK, I was *kind of* optimizing the wrong thing. Moving to Rc did make it faster, but the real problem was indeed allocating lots of tiny vecs in the `rk4` function. I'm sure there are still optimisations we can do in that whole routine - arclen / measure now being the big hotspot - but we're 25% faster than python/C++ now, so I'll take that.
