### ISSUE TITLE
Some other Rust projects

### ISSUE THREAD

**Issue by twardoch** [simoncozens/fonttools-rs#4]
There seems to be a competition to develop as many SFNT font parsers in Rust 😀

- https://github.com/RazrFalcon/ttf-explorer
- https://github.com/stone-zeng/rustotf
- https://github.com/yeslogic/allsorts
- https://github.com/pdf-rs/font
- https://github.com/manuel-rhdt/harfbuzz_rs

**Comment by simoncozens** [comment]
This one also writes.
