### ISSUE TITLE
tags and table access

### ISSUE THREAD

**Issue by cmyr** [simoncozens/fonttools-rs#45]
Playing around with this and I'm finding that the table access stuff is a bit of a headache, and I have a few thoughts for discussion:

## Tags

Having tag be a typealias for `[u8; 4]` works pretty well, but it has the one annoyance that tags can't be printed, because we can't impl `Display` for a typealias.

There is also the secondary issue that it is possible to construct tags that contain characters that are not permitted (outside the range `0x20`-`0x7E`) but I don't think this is a serious concern in practice.

If we want `Display`/`Debug` (which would be nice, lots of things are going to want to print tags) then we'll need a newtype, like:

```rust
struct Tag([u8; 4]);
```

but then we have the annoyance that every use of a tag will need to involve constructing one of these, like:

```rust
let GSUB = font.get_table(Tag::new("GSUB").unwrap());
```

and that's also annoying.

One alternative would be to have a bunch of `const`s for common tags, like:

```rust
pub mod tags {
    pub mod tables {
        const hhea: Tag = Tag(b"hhea");
        const head: Tag = Tag(b"head");
        // etc
    }
    pub mod features {
        // etc
    }
}
```

And then you might do things like,

```rust
let GPOS = font.get_table(tags::tables::GPOS);
```

and that feels kind of okay, but ultimately I don't love any of this.

## Tables

Table access is a bit annoying, because of the big `Table` enum. This has been worked around a bit by the `table_unchecked!` macro, but I wonder if we can make this a bit easier?

my thinking here would be to add a new `Tables` struct, and give it a bunch of convenience methods for the common tables, e.g:

```rust
struct Tables(BTreeMap<Tag, Table>);

impl Tables {
    pub fn gpos(&mut self) -> Result<Option<&GPOS>, DeserializationError> { };
   // ... etc
}
```

And then there could be a fallback method for getting an unknown table, that would just return bytes.

Doing this would also mean we wouldn't need to interact with raw tags as often.

**Comment by cmyr** [comment]
Oh one *very* fancy option we could do:

I'm pretty sure we could write a procedural `tag!` macro that would ensure, at compile time, that a tag was valid; then we would just write stuff like `tag!("GPOS")` or `tag!("URD")` and it would be fine, but `tag!("DURPP")` or `tag!("\n\n\0\0")` would just fail to compile.

This feels like overkill but if we're already exporting a bunch of procedural macros maybe it's not that bad...

**Comment by simoncozens** [comment]
One thing I've been thinking is that we should move to RefCells or similar to allow interior mutability. Currently because `get_table` lazily deserializes (and caches the deserialised object) it requires an `&mut` reference to the font - which makes it challenging to get more than one table at once.

**Comment by cmyr** [comment]
okay yea that probably makes sense.

I've been poking away at this a bit, will open some PRs to show some possible ideas.

**Comment by behdad** [comment]
Please keep it lazy. Both HarfBuzz and FontTools do it that way and it's essential to a multipurpose library.

**Comment by cmyr** [comment]
Sure, I'm just trying to think through our options.

**Comment by cmyr** [comment]
Just thinking out loud: what if we explicitly required the user to call a `deserialize` or `load_tables` method before accessing a table?

like:

```rust
pub fn load_tables(&mut self, tables: &[Tag]) -> Result<(), DeserializationError>;
```

This would let all `get_table`-style methods to just return `Option<&Table>` or whatever.

I don't love this API in general, but in the context of this crate maybe it's okay?

**Comment by cmyr** [comment]
also what about just having all the common tables be direct fields on the font object?

like,

```rust
struct Font {
    head: head,
    GSUB: Option<GSUB>,
    other: Map<Tag, Vec<u8>>,
    // etc
}
```

(There would still be some mechanism to do lazy loading, not depicted)

**Comment by simoncozens** [comment]
We need to keep the other tables around, though; first because we need to save what we loaded, and second, just because *we* don’t know how to interpret the data in those tables, doesn’t mean the library user doesn’t know how. Someone should be able to build eg a Graphite engine on top of tables we don’t recognise.

**Comment by cmyr** [comment]
I guess ultimately there's a bunch of design decisions to think about, and it comes down to knowing a bit more about the common use-cases.

- is it common to need to mutate an existing table in the font?
  - while holding a reference to some other table in the font?
- do we want to be able to share a single font object across multiple threads?

Only possible solution to a bunch of this is to use shared (reference counted) pointers to parsed tables...

**Comment by cmyr** [comment]
here's a sketch of one possible design.

- no `Tables` enum
- separate loading from access
- each known table gets its own accessors (e.g. `gvar()`, `gvar_mut()`)
- no transparent lazy loading, though

This is... okay. I could make this do actual lazy loading if I put all the tables/data behind `Rc`; the downside to that is that there could not be direct mutation, you would always need to clone the table you want to mutate, mutate it, and then put it back in the font.

```rust
struct Font {
    unloaded: BTreeMap<Tag, Vec<u8>>,
    loaded: BTreeMap<Tag, Box<dyn Any>>,
}

impl Font {
    fn load(&mut self, tag: Tag) -> Result<(), DeserializationError> {
        let data = match self.unloaded.remove(&tag) {
            Some(data) => data,
            None => return Ok(()),
        };

        let data: Box<dyn Any> = match tag.as_str() {
            "avar" => Box::new(otspec::de::from_bytes::<crate::avar::avar>(&data)?),
            "cmap" => Box::new(otspec::de::from_bytes::<crate::cmap::cmap>(&data)?),
            // other tables here
            other => Box::new(data),
        };
        self.loaded.insert(tag, data);
        Ok(())
    }

    fn load_tables(&mut self, tables: &[Tag]) -> Result<(), DeserializationError> {
        for tag in tables {
            self.load(*tag)?;
        }
        Ok(())
    }

    fn gpos(&self) -> Option<&crate::GPOS::GPOS> {
        self.get_typed(GPOS_TAG)
    }

    fn gpos_mut(&mut self) -> Option<&mut crate::GPOS::GPOS> {
        self.get_typed_mut(GPOS_TAG)
    }

    fn get_typed<T: Any>(&self, tag: Tag) -> Option<&T> {
        assert!(
            !self.unloaded.contains_key(&tag),
            "tables must be loaded before use"
        );
        self.loaded
            .get(&tag)
            .map(|t| t.downcast_ref().expect("wrong type for tag"))
    }

    fn get_typed_mut<T: Any>(&mut self, tag: Tag) -> Option<&mut T> {
        assert!(
            !self.unloaded.contains_key(&tag),
            "tables must be loaded before use"
        );
        self.loaded
            .get_mut(&tag)
            .map(|t| t.downcast_mut().expect("wrong type for tag"))
    }

    fn other_table(&self, tag: Tag) -> Option<&Vec<u8>> {
        // still requires you to load the table first :/
        self.get_typed(tag)
    }
}
```

**Comment by behdad** [comment]
You create blob for new gvar/glyf, then stick that into the *backing* of a new, immutable, Face.
